"""Regression checks for known hybrid and citation residue in live TeX."""

from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent

SUSPICIOUS_STRINGS = [
    "powerful Ho",
    "Father Chia",
    "Father Keng",
    "Father Hsin",
    "长 Kwangchih",
    "Yang 中-chien",
    "刘 董-sheng",
    "李 京-tan",
    "韦 and Yellow",
    "董 乙",
    "Huai 乙",
    "刘里-ke",
    "长 Kuang-",
    "长 光",
    "长 Tsungtung",
    "An 知-min",
    "Chan 并-leung",
    "Huang 蔡-chün",
    "Huang 京-hsin",
    "Kuan 谢楚",
    "Yü 邢-wu",
    "Lu 史-hsien",
    "董-tsuan",
    "中-hua jen-min",
    "乙-li",
    "刘-lu",
    "颜 Yün",
    "李 史",
    "金 祥-heng",
    "徐 chia-ku wenpien",
    "徐 chia-ku wen-pien",
    "乙-wen",
    "蛟城 chia-ku wen-pien",
    "Chin Hsiang-heng",
    "Hsü chia-ku wen-pien",
    "Chiao-cheng chia-ku wen-pien",
    r"\pinyinterm{jiaguwen-bian} \pinyinterm{jiaguwen-bian}",
    "the 安陽 site",
    "at 安陽 that",
    "安陽 fa-chiieh pao-kao",
    "安陽 remains",
    "安陽 material",
    "安陽 diviners",
    "The excavation at 小屯",
    "in the 小屯 area",
    "south of 小屯",
    "sites at 小屯",
    "For the description of 小屯",
    "Hsiao-t'un",
    "Ssu-ma Ch'ien",
    "Shih-ching",
    "San-t'ung-li",
    "Shang-shu",
    "Han-shu",
    "Shih-chi",
    "Tso-chuan",
    "Meng-tzu",
    "Ku-pen chu-shu chi-nien",
    "Ti-wang shih-chi",
    "wang chan yüeh",
    "wang chan pu yüeh",
    "Que, Pin, 成",
    "Hsüan E, and 中 [?]",
    "Lü, 邢",
    "Yin, 楚",
    "Pin and 成",
    "divinations of 成",
    "diviner 乙's inscriptions",
    "diviner 中 +",
    "diviner 邢",
    "Xiong, Ta, and 楚",
    "李 大 [1972]",
    "焦 [1959]",
    "长 拼'ü",
    "Wu 史-ch'ang",
    "ta yi Shang ★ē",
    "guiyou}, 成 divined",
    "知 郭",
    "知郭",
    "Wang 成",
    "夏 韦",
    "中-kuo k'e-hsüeh-yüan k'ao-ku yen-chiu-so ‹† 國科學院",
    r"\pinyinterm{kaogu}-hsüeh chuan-k'an yi-chung ti-shih-ssu hao \pinyinterm{kaogu}學專刋乙種第十四號",
    "中-yang yen-chiu-yüan lishih yü-yen yen-chiu-so chuan-k'an chih wu-shih",
    "中-kuo wen-tzu X‡",
    r"\pinyinterm{li-xiaoting} *",
    r"\pinyinterm{jiaguwenzi-jishi} X",
    "甲骨-hsüeh cannot be divorced from chin-shih-hsüeh",
    "yüanë",
    "島 Sōrui",
    "島 Kunio",
    "Shima's Sōrui",
    "Shima Kunio. Inkyo bokuji sōrui, 2d rev. ed.",
    "With the exception of the references to Shima's Inkyo bokuji sōrui",
    "Bernhard Karlgren, Grammata Serica Recensa",
    "Tōdō Akiyasu, Kanji gogen jiten",
    "Katō Joken, Kanji no kigen",
    "Particularly useful are Grammata Serica Recensa",
    "Hsu chia-ku nien-piao",
    "Hsü chia-ku nien-piao",
    "徐 chia-ku nien-piao",
    "徐-pu",
    "董 [1954a]",
    "Houpien 2.9.1",
    "Houpien 2.41.12",
    "chia-ku-wen",
    "chia-ku transcriptions",
    "steeped in chia-ku-wen",
    "Ti will approve",
    "Ti will not assist and approve",
    "the role of Ti in such divinations",
    "come from Ti, the high",
    "that Ti was not specifically mentioned",
    "史赤ng",
    "铁阴ün 23.4",
    "陳 知-mai",
    "As 陳 notes",
    "铁-hsin reprints",
    "董 and 金 [1961]",
    "中-kuo wen-tzu",
    "史-yi",
    "史陶 2.92",
    "铁阴i",
    "铁阴ü",
    "铁阴ün 108.1",
    "graphs 1 and 2 may be read as chia-hsü",
    "pu shou nien",
    "the phrase t'ien kuan",
    "with t'ien having the sense either of \"hunt\"",
    "the second graph is nien",
    "he identifies as ch'iu",
    "was ancestral to ch'ou",
    "Quch divined:",
    "Ch üeh divined:",
    "Chih Kuo",
    "Hsia Wei",
    "Hsü-pien",
    "Hsüan",
    "Fu Hsi",
    "Hsia Nai",
    "Hsinhua-she",
    "k'ao-shih, p. 265",
]


def test_no_known_hybrid_name_residue_in_live_tex():
    offenders = []

    for path in (REPO_ROOT / "tex").rglob("*.tex"):
        text = path.read_text(encoding="utf-8")
        for needle in SUSPICIOUS_STRINGS:
            if needle in text:
                offenders.append(f"{path.relative_to(REPO_ROOT)}: {needle}")

    assert not offenders, "Found hybrid residue:\n" + "\n".join(offenders)
