#!/usr/bin/env python3
"""Render a safe LaTeX version of Bibliography A from data/abbreviations.yml."""

from __future__ import annotations

import re
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
INPUT = ROOT / "data" / "abbreviations.yml"
OUTPUT = ROOT / "tex" / "backmatter" / "abbreviations_live.tex"

FIELD_RE = re.compile(r"^\s{4}(body_tesseract|gv_excerpt|gv_cjk):\s*(.*)$")
ABBR_RE = re.compile(r"^\s{2}- abbr:\s*(.*)$")


def parse_scalar(raw: str) -> str:
    raw = raw.strip()
    if not raw:
        return ""
    if len(raw) >= 2 and raw[0] == raw[-1] and raw[0] in {"'", '"'}:
        raw = raw[1:-1]
        if raw and raw[0] == raw[-1] == "'":
            raw = raw[1:-1]
        raw = raw.replace("''", "'").replace('\\"', '"')
    return " ".join(raw.split())


def escape_tex(text: str) -> str:
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(ch, ch) for ch in text)


def load_entries() -> list[dict[str, str]]:
    entries: list[dict[str, str]] = []
    current: dict[str, str] | None = None

    for line in INPUT.read_text(encoding="utf-8").splitlines():
        abbr_match = ABBR_RE.match(line)
        if abbr_match:
            if current:
                entries.append(current)
            current = {"abbr": parse_scalar(abbr_match.group(1))}
            continue

        field_match = FIELD_RE.match(line)
        if field_match and current is not None:
            current[field_match.group(1)] = parse_scalar(field_match.group(2))

    if current:
        entries.append(current)

    return entries


def render_entry(entry: dict[str, str]) -> str:
    body = entry.get("body_tesseract") or entry.get("gv_excerpt") or "[description pending]"
    cjk = entry.get("gv_cjk", "")

    rendered = f"  \\item[{escape_tex(entry['abbr'])}] {escape_tex(body)}"
    if cjk:
        rendered += rf" \hfill\textit{{[CJK: {escape_tex(cjk)}]}}"
    return rendered


def main() -> None:
    entries = load_entries()
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "% Generated by scripts/render_abbreviations_tex.py.",
        r"\section*{Oracle-Bone Collections Cited and Their Abbreviations}",
        r"\addcontentsline{toc}{section}{Oracle-Bone Collections Cited and Their Abbreviations}",
        "",
        r"\begin{description}",
    ]
    lines.extend(render_entry(entry) for entry in entries if entry.get("abbr"))
    lines.append(r"\end{description}")
    lines.append("")

    OUTPUT.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
